version: '3.1'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    command: sh -c "composer install && apache2-foreground"

  mysql:
    image: mysql:9.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: myapp
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    ports:
      - 3306:3306
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.2
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=0

volumes:
  db_data:
      